services:
  app:
    build:
      context: ./frontend/marthurt-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/marthurt-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
