services:
  backend:
    build:
      context: ./backend/restapi
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    command: mvn spring-boot:run
    volumes:
      - ./backend/restapi:/app
      - ~/.m2:/root/.m2

  frontend:
    build:
      context: ./frontend/marthurt-frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: npm run dev
    volumes:
      - ./frontend/marthurt-frontend:/app
      - /app/node_modules
